version: "3"

services:
  web:
    restart: always
    build: .
    ports:
      - 8080:8000
    expose:
      - "8000"
    volumes:
      - ./app:/src/app
      - static_volume:/src/app/static  # <-- bind the static volume
    links:
      - crmfood_db:crmfood_db
    command: >
      sh -c "cd app/ && gunicorn --bind :8000 app.wsgi:application"
    env_file:
      - .env
    depends_on:
      - crmfood_db

  nginx:
    image: nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - .ngix/mysite.template:/etc/nginx/conf.d/mystie.template
      - static_volume:/src/app/static
    links:
      - web:web
    depends_on:
      - web

  crmfood_db:
    restart: always
    image: postgres:11-alpine
    volumes:
#      - postgres_data:/var/lib/postgresql/data/
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./backups/postgresql:/backup
    env_file:
      - .env
    expose:
      - "5432"

volumes:
  postgres_data:
  static_volume:
