# Generated by Django 2.2.6 on 2019-12-11 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0002_order'),
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecificMeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('meal_id',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specific_meals',
                                   to='meals.Meal')),
                ('order_id',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specific_meals',
                                   to='orders.Order')),
            ],
        ),
    ]
