# Generated by Django 2.2.6 on 2019-12-11 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_remove_specificmeal_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificmeal',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals_id', to='orders.Order'),
        ),
    ]
