# Generated by Django 2.2.6 on 2019-12-11 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='table_name',
        ),
    ]
