# Generated by Django 2.2.8 on 2019-12-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0003_remove_order_table_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
