# Generated by Django 2.2.8 on 2019-12-13 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0004_auto_20191213_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('service_fee', models.IntegerField()),
                ('total_sum', models.IntegerField()),
                ('order_id',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_check',
                                      to='orders.Order')),
            ],
        ),
    ]
