# Generated by nginx.conf 2.2.8 on 2020-01-01 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_all', to='orders.Order'),
        ),
    ]
